const $=s=>document.querySelector(s); const state={token:localStorage.getItem("pam_token"),user:null,view:"resources",data:{},session:null,socket:null,heartbeat:null};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(message){const node=document.createElement("div");node.textContent=message;$("#toast").append(node);setTimeout(()=>node.remove(),4000)}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:body.detail?.message||`HTTP ${response.status}`)}return response.status===204?null:response.json()}
async function apiBlob(path){const response=await fetch(path,{headers:{Authorization:`Bearer ${state.token}`}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:body.detail?.message||`HTTP ${response.status}`)}return response.blob()}
const badge=(type)=>`<span class="badge ${type==="web"?"text-bg-info":"text-bg-primary"} protocol">${esc(type)}</span>`;
async function load(){state.data.resources=await api("/api/resources");state.data.groups=await api("/api/resource-groups");state.data.profiles=await api("/api/access-profiles");state.data.requests=await api("/api/access-requests");state.data.grants=await api("/api/access-grants");state.data.sessions=await api("/api/sessions");render()}
function render(){document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===state.view));const fn={resources,requests,grants,sessions}[state.view];fn()}
function resources(){
  $("#filters").innerHTML=`<div class="col-md-3"><select id="typeFilter" class="form-select"><option value="">All protocols</option><option>ssh</option><option>web</option></select></div><div class="col-md-3"><input id="envFilter" class="form-control" placeholder="Environment"></div><div class="col-md-3"><select id="groupFilter" class="form-select"><option value="">All groups</option>${state.data.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join("")}</select></div><div class="col-md-3"><select id="criticalFilter" class="form-select"><option value="">All criticalities</option>${["low","medium","high","critical"].map(x=>`<option>${x}</option>`).join("")}</select></div>`;
  const draw=()=>{const values={type:$("#typeFilter").value,env:$("#envFilter").value.toLowerCase(),group:$("#groupFilter").value,critical:$("#criticalFilter").value};const rows=state.data.resources.filter(r=>(!values.type||r.resource_type===values.type)&&(!values.env||r.environment.toLowerCase().includes(values.env))&&(!values.group||String(r.group_id)===values.group)&&(!values.critical||r.criticality===values.critical));$("#content").innerHTML=`<div class="resource-grid">${rows.map(r=>`<article class="resource-card">${badge(r.resource_type)}<h2 class="h5 mt-2">${esc(r.name)}</h2><p class="text-secondary">${esc(r.description||"No description")}</p><div class="small mb-3">${esc(r.environment)} · ${esc(r.group_name||"Ungrouped")} · ${esc(r.criticality)}</div><button class="btn btn-primary btn-sm" data-request="${r.id}">Request access</button><button class="btn btn-outline-secondary btn-sm" data-details="${r.id}">Details</button></article>`).join("")}</div>`};document.querySelectorAll("#filters input,#filters select").forEach(x=>x.addEventListener("input",draw));draw()}
function table(headers,rows){return `<div class="table-responsive"><table class="table table-hover"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`}
function requests(){$("#filters").innerHTML="";$("#content").innerHTML=table(["Resource","User","Reason","Duration","Status","Action"],state.data.requests.map(x=>`<tr><td>${esc(x.resource_name)}</td><td>${esc(x.username)}</td><td>${esc(x.reason)}</td><td>${x.requested_duration_minutes}m</td><td>${esc(x.status)}</td><td>${x.status==="pending"&&state.user.role!=="user"?`<button data-approve="${x.id}" class="btn btn-sm btn-success">Approve</button>`:""}</td></tr>`))}
function grants(){$("#filters").innerHTML="";$("#content").innerHTML=table(["Resource","Protocol","Valid to","Status","Action"],state.data.grants.map(x=>`<tr><td>${esc(x.resource_name)}</td><td>${badge(x.resource_type)}</td><td>${new Date(x.valid_to).toLocaleString()}</td><td>${esc(x.status)}</td><td>${x.status==="active"?`<button data-launch="${x.id}" class="btn btn-sm btn-primary">Launch session</button>`:""}</td></tr>`))}
function sessions(){$("#filters").innerHTML="";$("#content").innerHTML=table(["Resource","User","Protocol","Started","Status","Action"],state.data.sessions.map(x=>`<tr><td>${esc(x.resource_name)}</td><td>${esc(x.username)}</td><td>${badge(x.protocol)}</td><td>${x.started_at?new Date(x.started_at).toLocaleString():"—"}</td><td>${esc(x.status)}</td><td><button data-replay="${x.id}" class="btn btn-sm btn-outline-info">Replay</button>${x.status==="active"?` <button data-resume="${x.id}" class="btn btn-sm btn-primary">Resume</button>`:""}</td></tr>`))}
async function requestAccess(resourceId){const resource=state.data.resources.find(x=>x.id===resourceId);const profiles=state.data.profiles.filter(x=>!x.resource_type||x.resource_type===resource.resource_type);const reason=prompt("Reason for access:");if(!reason)return;const profile=profiles[0];if(!profile)throw new Error("No matching access profile");await api("/api/access-requests",{method:"POST",body:JSON.stringify({resource_id:resource.id,access_profile_id:profile.id,reason,requested_duration_minutes:Math.min(60,profile.max_session_duration_minutes)})});await load();state.view="requests";render()}
async function launch(grantId){const created=await api("/api/sessions",{method:"POST",body:JSON.stringify({grant_id:grantId})});const launched=await api(`/api/sessions/${created.id}/launch`,{method:"POST"});openViewer(launched)}
function connectSocket(){const session=state.session;if(!session)return;const scheme=location.protocol==="https:"?"wss":"ws";state.socket=new WebSocket(`${scheme}://${location.host}${session.stream_url}?token=${encodeURIComponent(session.stream_token)}`);if(session.protocol==="web")state.socket.onmessage=e=>{$("#browserFrame").src=`data:image/jpeg;base64,${JSON.parse(e.data).data}`};else{state.socket.binaryType="arraybuffer";state.socket.onmessage=e=>{$("#terminalOutput").textContent+=typeof e.data==="string"?e.data:new TextDecoder().decode(e.data);$("#terminalOutput").scrollTop=$("#terminalOutput").scrollHeight}}}
function openViewer(session){state.session=session;$("#shell").classList.add("d-none");$("#viewer").classList.remove("d-none");$("#viewerTitle").textContent=`${session.protocol.toUpperCase()} session #${session.id}`;$("#browserStage").classList.toggle("d-none",session.protocol!=="web");$("#terminalStage").classList.toggle("d-none",session.protocol!=="ssh");connectSocket();let ticks=0;state.heartbeat=setInterval(async()=>{try{await api(`/api/sessions/${session.id}/heartbeat`,{method:"POST"});if(++ticks%2===0){const renewed=await api(`/api/sessions/${session.id}/stream-token`,{method:"POST"});state.session.stream_token=renewed.stream_token;if(state.socket)state.socket.close();connectSocket()}}catch{closeViewer()}},20000)}
async function input(event){if(!state.session||state.session.protocol!=="web")return;await api(`/api/web-sessions/${state.session.id}/input`,{method:"POST",body:JSON.stringify({token:state.session.stream_token,event})})}
const frame=$("#browserFrame");frame.addEventListener("click",e=>{const b=frame.getBoundingClientRect();input({type:"mouse",action:"click",x:(e.clientX-b.left)*1440/b.width,y:(e.clientY-b.top)*900/b.height})});frame.addEventListener("wheel",e=>{e.preventDefault();input({type:"wheel",delta_x:e.deltaX,delta_y:e.deltaY})},{passive:false});document.addEventListener("keydown",e=>{if(!$("#viewer").classList.contains("d-none")&&state.session?.protocol==="web"){e.preventDefault();input({type:"key",action:"down",key:e.key})}});document.addEventListener("keyup",e=>{if(!$("#viewer").classList.contains("d-none")&&state.session?.protocol==="web")input({type:"key",action:"up",key:e.key})});
$("#terminalInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&state.socket){state.socket.send(e.target.value+"\n");e.target.value=""}});
function closeViewer(){if(state.socket)state.socket.close();clearInterval(state.heartbeat);state.socket=null;state.session=null;$("#viewer").classList.add("d-none");$("#shell").classList.remove("d-none");load().catch(e=>toast(e.message))}
async function replay(id){const [session,events,artifacts]=await Promise.all([api(`/api/sessions/${id}`),api(`/api/sessions/${id}/events`),api(`/api/sessions/${id}/artifacts`).catch(()=>[])]);$("#shell").classList.add("d-none");$("#replay").classList.remove("d-none");$("#replayTitle").textContent=`Session #${id} replay`;$("#replayMeta").innerHTML=[["Resource",session.resource.name],["User",state.data.sessions.find(x=>x.id===id)?.username],["Request",session.request.id],["Grant",session.grant.id]].map(([a,b])=>`<div class="col-md-3"><div class="meta-card"><small class="text-secondary">${a}</small><div>${esc(b)}</div></div></div>`).join("");const video=artifacts.find(x=>x.artifact_type==="video");if(video){const blob=await apiBlob(`/api/sessions/${id}/artifacts/${video.id}/play`);$("#replayVideo").src=URL.createObjectURL(blob)}else $("#replayVideo").removeAttribute("src");const types=[...new Set(events.map(e=>e.event_type))];$("#eventFilter").innerHTML=`<option value="">All events</option>${types.map(x=>`<option>${esc(x)}</option>`).join("")}`;const draw=()=>{$("#timeline").innerHTML=events.filter(x=>!$("#eventFilter").value||x.event_type===$("#eventFilter").value).map(x=>`<button data-time="${Math.max(0,(new Date(x.timestamp)-new Date(session.started_at))/1000)}"><strong>${esc(x.event_type)}</strong><br><small>${new Date(x.timestamp).toLocaleTimeString()} · ${esc(x.source)}</small></button>`).join("")};$("#eventFilter").onchange=draw;draw();$("#timeline").onclick=e=>{const b=e.target.closest("button");if(b)$("#replayVideo").currentTime=Number(b.dataset.time)};$("#replayTerminate").classList.toggle("d-none",session.status!=="active");$("#replayTerminate").onclick=()=>terminate(id)}
async function terminate(id=state.session?.id){if(!id)return;await api(`/api/sessions/${id}/terminate`,{method:"POST",body:JSON.stringify({reason:"Terminated from PAM UI"})});closeViewer()}
document.body.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;try{if(b.dataset.view){state.view=b.dataset.view;render()}if(b.dataset.request)await requestAccess(Number(b.dataset.request));if(b.dataset.details){const r=state.data.resources.find(x=>x.id===Number(b.dataset.details));alert(`${r.name}\n${r.description||""}\nDomains: ${(r.allowed_domains||[]).join(", ")}`)}if(b.dataset.approve){await api(`/api/access-requests/${b.dataset.approve}/approve`,{method:"POST",body:"{}"});await load()}if(b.dataset.launch)await launch(Number(b.dataset.launch));if(b.dataset.replay)await replay(Number(b.dataset.replay))}catch(err){toast(err.message)}});
$("#terminate").onclick=()=>terminate();$("#closeViewer").onclick=closeViewer;$("#closeReplay").onclick=()=>{$("#replay").classList.add("d-none");$("#shell").classList.remove("d-none")};$("#logout").onclick=async()=>{try{await api("/api/auth/logout",{method:"POST"})}catch{}localStorage.removeItem("pam_token");location.reload()};
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{const result=await api("/api/auth/login",{method:"POST",body:JSON.stringify({username:$("#username").value,password:$("#password").value,provider:"local_db"})});state.token=result.access_token;localStorage.setItem("pam_token",state.token);await start()}catch(err){toast(err.message)}};
async function start(){state.user=await api("/api/auth/me");$("#identity").textContent=`${state.user.username} · ${state.user.role}`;$("#login").classList.add("d-none");$("#shell").classList.remove("d-none");await load()}if(state.token)start().catch(()=>{localStorage.removeItem("pam_token");state.token=null});
